### PR TITLE
GTK 3/Python 3 port fixes

### PR DESCRIPTION
**Pull request by hadess**
I'm fine with you squashing those into your patch, thanks!

### CODE REVIEW

**Comment by hadess** [comment]
Sorry, this was meant to be a PR against @hfiguiere's port/fork, but feel free to squash my patches into the first patch in the MR.

**Comment by hfiguiere** [comment]
Feel free to take my original patch part of this PR. I had forgotten about that.

**Comment by hguemar** [comment]
works as expected

**Comment by btimofeev** [comment]
Thank you

**Pull request merged**
